name: build
on: push

jobs: 
    builds:
      runs-on: ubuntu-latest
      steps:
          - name: la famille
            uses: actions/checkout@v3
          - name: installer NodeJS
            uses: actions/setup-node@v3
